 export const stations = [
    {stationAddress: "935 Folsom at 5th Street", battalionCode:'B01' , stationNumber:1 },
    {stationAddress: "1340 Powell Street at Broadway" ,battalionCode:'B02' , stationNumber:2  },
    {stationAddress: "1067 Post Street at Polk Street" ,battalionCode:'B03' , stationNumber:3  },
    {stationAddress: " 449 Mission Rock at 3rd Street" ,battalionCode:'B04' , stationNumber:4  },
    {stationAddress:  "1301 Turk Street at Webster Street" ,battalionCode:'B05' , stationNumber:5  },
    {stationAddress:  "135 Sanchez Street at Henry Street" ,battalionCode:'B06' , stationNumber:6  },
    {stationAddress:  "2300 Folsom Street at 19th Street" ,battalionCode:'B07' , stationNumber:7  },
    {stationAddress:  "36 Bluxome Street at 4th Street" , battalionCode:'B08' , stationNumber:8  },
    {stationAddress:  "2245 Jerrold Avenue at Upton Street" , battalionCode:'B09' , stationNumber:9  },
    {stationAddress:  "655 Presidio Avenue at Bush Street" , battalionCode:'B10' , stationNumber:10  },
    {stationAddress: "3880 26th Street at Church Street" , battalionCode:'B11' , stationNumber:11  },
    {stationAddress: "1145 Stanyan Street at Grattan Street" , battalionCode:'B12' , stationNumber:12  },
    {stationAddress:  "530 Sansome Street at Washington Street" , battalionCode:'B13' , stationNumber:13  },
    {stationAddress:  "551 26th Avenue at Geary Boulevard" , battalionCode:'B14' , stationNumber:14  },
    {stationAddress: "1000 Ocean Avenue at Phelan Avenue" , battalionCode:'B15' , stationNumber:15  },
    {stationAddress:  "2251 Greenwich Street at Fillmore Street" , battalionCode:'B16' , stationNumber:16  },
    {stationAddress: "1295 Shafter Avenue at Ingalls Street" , battalionCode:'B17' , stationNumber:17 },
    {stationAddress:  "1935 32nd Avenue at Ortega Street" , battalionCode:'B18' , stationNumber:18  },
    {stationAddress:  "390 Buckingham Way at Winston Street" , battalionCode:'B19' , stationNumber:19  },
    {stationAddress:  "285 Olympia Way at Clarendon Avenue" , battalionCode:'B20' , stationNumber:20  },
    {stationAddress:  "1443 Grove Street at Broderick Street" , battalionCode:'B21' , stationNumber:21  },
    {stationAddress:  "1290 16th Avenue at Irving Street" , battalionCode:'B22' , stationNumber:22  },
    {stationAddress:  "1348 45th Avenue at Judah Street" , battalionCode:'B23' , stationNumber:23  },
    {stationAddress:  "100 Hoffman Avenue at Alvarado Street" , battalionCode:'B24' , stationNumber:24  },
    {stationAddress:  "3305 3rd Street at Cargo Way" , battalionCode:'B25' , stationNumber:25  },
    {stationAddress:  "80 Digby Street at Addison Street" , battalionCode:'B26' , stationNumber:26  },
    {stationAddress:  "1814 Stockton Street at Greenwich Street" , battalionCode:'B28' , stationNumber:28  },
    {stationAddress:  "299 Vermont Street at 16th Street" , battalionCode:'B29' , stationNumber:29  },
    {stationAddress:  "441 12th Avenue at Geary Boulevard" , battalionCode:'B31' , stationNumber:31  },
    {stationAddress:  "194 Park Street at Holly Park Circle" , battalionCode:'B32' , stationNumber:32  },
    {stationAddress:  "8 Capitol Avenue at Sagamore Street" , battalionCode:'B33' , stationNumber:33  },
    {stationAddress:  "499 41st Avenue at Geary Boulevard" , battalionCode:'B34' , stationNumber:34  },
    {stationAddress:  "Pier 22½, The Embarcadero at Harrison Street" , battalionCode:'B35' , stationNumber:35  },
    {stationAddress:  "109 Oak Street at Franklin Street" , battalionCode:'B36' , stationNumber:36  },
    {stationAddress:  "798 Wisconsin Street at 22nd Street" , battalionCode:'B37' , stationNumber:37  },
    {stationAddress:  "2150 California Street at Laguna Street" , battalionCode:'B38' , stationNumber:38  },
    {stationAddress:  "1091 Portola Drive at Miraloma Drive" , battalionCode:'B39' , stationNumber:39  },
    {stationAddress:  "2155 18th Avenue at Rivera Street" , battalionCode:'B40' , stationNumber:40  },
    {stationAddress:  "1325 Leavenworth Street at Jackson Street" , battalionCode:'B41' , stationNumber:41  },
    {stationAddress:  "2430 San Bruno Avenue at Silver Avenue" , battalionCode:'B42' , stationNumber:42  },
    {stationAddress:  "720 Moscow Street at France Avenue" , battalionCode:'B43' , stationNumber:43 },
    {stationAddress:  "1298 Girard Street at Wilde Avenue" , battalionCode:'B44' , stationNumber:44  },
    {stationAddress:  "800 Avenue I at 10th Street, Treasure Island" , battalionCode:'B48' , stationNumber:48  },
    {stationAddress:  "1415 Evans Avenue at Mendell Street" , battalionCode:'B49' , stationNumber:49  },
    {stationAddress: "218 Lincoln Blvd at Keyes Avenue", battalionCode:'B51' , stationNumber:51 }
]